version: '3'
services:
  db:
    image: 'postgres:10'
    container_name: 'db'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=json_faker'
    ports:
      - 5432:5432
  app:
    image: 'danielmarandici/jsonfaker:latest'
    container_name: 'jsonfakerapp'
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/json_faker
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update