spring:
  liquibase:
    enabled: true
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/liquitest
    username: postgres
    password: postgres

server:
  ssl:
    # keystore format, could be also JKS
    key-store-type: PKCS12
    # The path to the keystore containing the certificatekeystore/baeldung.p12
    key-store: classpath:keystore/baeldung.p12
    # password used to generate the certificate
    key-store-password: daniel
    key-alias: baeldung
    enabled: true
  port: 8443

facker:
  uri: https://jsonplaceholder.typicode.com/users


jwt:
    jwtCookie: jsonfaker
    jwtSecret : jsonfakerSecretKey
    jwtExpirationMs : 1800000
