
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fakejson
    password: postgres
    username: postgres
facker:
  uri: https://jsonplaceholder.typicode.com/users
logging:
  file:
    path: C:\logs
