server:
  port: 8443
  ssl:
    # keystore format, could be also JKS
    key-store-type: PKCS12
    # The path to the keystore containing the certificatekeystore/baeldung.p12
    key-store: classpath:keystore/baeldung.p12
    # password used to generate the certificate
    key-store-password: daniel
    key-alias: baeldung
    enabled: true